### ISSUE TITLE
custom_updater

### ISSUE THREAD

**Issue by backisen** [atomic7777/atomic_calendar#1]
Can you make this component sync with custom_updater and possible to update that way?

**Comment by atomic7777** [comment]
For now it should be working by manual adding entry in configuration - custom_updater:
```
   card_urls:
   - https://raw.githubusercontent.com/atomic7777/atomic_calendar/master/tracker.json
```
    
I've never used custom_updater, so I need to read about it (is there some global tracker database? I have to check it)

**Comment by backisen** [comment]
Thank you.
You can read more about it here:
[https://github.com/custom-components/custom_updater/wiki/How-it-works]

**Comment by freegink** [comment]
@atomic7777  Just need to create a pull request here. 
https://github.com/ludeeus/customjson/pulls

It would be very helpful if this awesome card is added in the list. Really appreciate it.

**Comment by freegink** [comment]
@atomic7777  Thanks for implementing custom_updater. You may close this issue.
