### ISSUE TITLE
Two recommendations

### ISSUE THREAD

**Issue by freegink** [atomic7777/atomic_calendar#10]
@atomic7777  Really like your work. I have two recommendations for the full calendar mode that you may consider.

1. Use the arrows to enclose the Month. It should still look good when showMonth is false. This way the card becomes more compact and looks more organised.

2. Make the last row of days configurable. Users can configure it as per their preferences.

![image](https://user-images.githubusercontent.com/3389244/56009726-d048af00-5cae-11e9-83de-0eef873e8534.png)

**Comment by atomic7777** [comment]
Thanks! Your suggestions are perfect. I wouldn't have thought of that. Simple and clear.
And about the last line, I will make it optional - but of course the calendar height will change sometimes.
I'll do it in next version, probably this weekend

**Comment by freegink** [comment]
Thanks very much. Really appreciate it.

**Comment by freegink** [comment]
@atomic7777  Thanks for making the changes.
