### ISSUE TITLE
timeSize 

### ISSUE THREAD

**Issue by rabbit52068** [atomic7777/atomic_calendar#11]
Hi @atomic7777 , thanks for making such a great custom card!

Just want to point out the option `timeSize` effects to all the cards.
Actually the statement above is not quite right.
I've set the `timeSize` to one of the calendar card but not the others.
Whichever the calendar card loaded first, the others will disregard it own setting.

Hope that makes sense to you and pardon my poor english.
All I wanted is to hide the `All day` text lol

Anyway, thanks again for the awesome work!

**Comment by atomic7777** [comment]
I made a big mistake. The configuration was loaded after the calendar, so it was not correct for the first one (it you have more).
Now it should work, but it can breaks some things when users already made some custom changes
