### ISSUE TITLE
Add support HACS

### ISSUE THREAD

**Issue by pepeEL** [atomic7777/atomic_calendar#13]
Hi
Is any chance to add support to HACS ?

**Comment by pepeEL** [comment]
Only owner can add this to HACS
https://github.com/custom-components/hacs/pull/85

**Comment by isabellaalstrom** [comment]
Would also like this! As of now I can't even add it as a custom repo.

**Comment by jameshiscott** [comment]
Yes, please support HACS, makes keeping this up-to-date so much easier.

**Comment by atomic7777** [comment]
It should work with the latest update, just add a custom repo as a plugin in HACS settings:
https://github.com/atomic7777/atomic_calendar
You still need to add this to lovelace config:
  - url: /community_plugin/atomic_calendar/atomic_calendar.js
    type: module

**Comment by peternijssen** [comment]
Thanks! You can also request HACS to add your repository by default;
https://custom-components.github.io/hacs/developer/include_default_repositories/

Saves everyone a step and everyone can find your plugin better :)

**Comment by atomic7777** [comment]
Added to HACS repository (will be there in future hacs releases)

**Comment by pepeEL** [comment]
thanks
