### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by tenkaibr** [atomic7777/atomic_calendar#21]
Would it be possible to create a separate file containing the days of the week, months and etc so that they could be translated? So every time the addon was updated I would not have to manually change the file.

**Comment by atomic7777** [comment]
How do you change it manually? There are no week / month names in this app. It uses moment.js library (international, multi-language version) so it uses day names in the selected language (selected in HA). Isn't that working for you?
I could add a setting to force change language if anyone needs it.

**Comment by jhbcosta** [comment]
Hi. Is it possible to force using specific language? I am from Brazil and my language is 'pt-br' but my calendar is presenting dates in English. Thanks.

**Comment by atomic7777** [comment]
Is your Home Assistant in Portugese? Calendar uses HA language, and it works for everyone as far as I know. If this is not working for you, I'll look and make an option to force it.

**Comment by jhbcosta** [comment]
Yes, my HA is in Portuguese. Calendar only works when I select portuguese from Portugal (pt) in the language list. If I select Portuguese (Brazil) (pt-BR) it gets back to English. Thanks.

**Comment by tenkaibr** [comment]
> How do you change it manually? There are no week / month names in this app. It uses moment.js library (international, multi-language version) so it uses day names in the selected language (selected in HA). Isn't that working for you?
> I could add a setting to force change language if anyone needs it.

I did not know about that. But I can confirm that the pt-br language does not work. Maybe it would be the case to just add it?

**Comment by jhbcosta** [comment]
It is easy to simulate the issue. Go to your HA profile (clicking on your INITIALs on the left top) and then select "PORTUGUESE" in the language list. Then go back to the CALENDAR and ctrl + f5 on it and you will see labels in portuguese (which is fine but portuguese from Portugal). Then, get back to the language list and select "PORTUGUESE (BRAZIL)", go back to the CALENDAR and ctrl + f5 again and you will see labels in ENGLISH (which is not OK). Thanks.

**Comment by atomic7777** [comment]
Thanks for reporting. I found why it was happening.
Home Assistant sets your language to "pt-BR" while moment.js library wants the setting in lower case "pt-br".
It should be fixed now in v0.8.4. Anyway, I added an option to set language in config:
```language: 'pt-br'``` 
but you shouldn't need it now.

**Comment by pepeEL** [comment]
Hi
But where we can read what language code is used on our HA ? I dont know what i must setup in config Calendar....

**Comment by atomic7777** [comment]
It's using your HA language (Polist in this case) but it's only translating week/month names. (czerwiec lipiec środa etc)
There are few custom strings you need to translate by yourself in calendar configuration, in ui-lovelace.yaml:
```
			title: 'Kalendarz', // Card title
			fullDayEventText: 'Cały dzień', // "All day" custom text
			untilText: 'Do', // "Until" custom text

```

**Comment by tenkaibr** [comment]
Well, I tested the new version but I did not succeed. I tried to change manually but also but did not succeed. For some reason it seems to me that the system is in English and is not recognizing the language selected by the user. I even tried to switch to other languages ​​and the calendar remained in English.

Another thing I noticed was in relation to the filename. One version is with hyphens and the other with underline. I think you should change this because I thought the last version was not working but it was just an error in the file name.

![image](https://user-images.githubusercontent.com/39348260/60877128-976b9800-a213-11e9-8d0a-f73e5f149477.png)

**Comment by atomic7777** [comment]
I had to change the file name to atomic_calendar, because of HACS requirements (file name needs to be same as repository name)
It should work now, because I didn't update the file correctly in 0.8.4, so now it's 0.8.5 and it should work. Sorry

**Comment by pepeEL** [comment]
> It's using your HA language (Polist in this case) but it's only translating week/month names. (czerwiec lipiec środa etc)
> There are few custom strings you need to translate by yourself in calendar configuration, in ui-lovelace.yaml:
> 
> ```
> 			title: 'Kalendarz', // Card title
> 			fullDayEventText: 'Cały dzień', // "All day" custom text
> 			untilText: 'Do', // "Until" custom text
> ```

But how i can do it ?

**Comment by tenkaibr** [comment]
> I had to change the file name to atomic_calendar, because of HACS requirements (file name needs to be same as repository name)
> It should work now, because I didn't update the file correctly in 0.8.4, so now it's 0.8.5 and it should work. Sorry

I tried the new version but I did not succeed either. As I said earlier, no other language is being applied except English. Maybe I have to change my language somewhere else.

As for the filename, it would be interesting to change the installation guide then:

From:
```
resources:
  - url: /local/atomic-calendar.js
    type: module

```
to:

```
resources:
  - url: /local/atomic_calendar.js
    type: module
```

**Comment by atomic7777** [comment]
Do you have v0.8.5? Could you check in the console? (F12 / console - it should say "atomic calendar v0.8.5 loaded") Try to ctrl-F5
Thanks for the readme guide error, it's fixed now

**Comment by tenkaibr** [comment]
It is. I do not know what to do... lol

![image](https://user-images.githubusercontent.com/39348260/60881938-321ca480-a21d-11e9-9870-3119686ec7ac.png)

Even switching to French permance in English

![image](https://user-images.githubusercontent.com/39348260/60882050-6f813200-a21d-11e9-9fe8-b3f276bf677a.png)

**Comment by tenkaibr** [comment]
My mistake. Apparently some expressions have to be translated manually. I'll try to find a tutorial for this.

**Comment by atomic7777** [comment]
Do you mean your events are not showing? Do you have any events?
Or you mean it's in English?
If it's only about language you have to put a custom message in your config:
`noEventsForTodayText: 'No events for today custom text in your language'`

**Comment by tenkaibr** [comment]
> Do you mean your events are not showing? Do you have any events?
> Or you mean it's in English?
> If it's only about language you have to put a custom message in your config:
> `noEventsForTodayText: 'No events for today custom text in your language'`
> 
> everything is in readme, but I know it's a mess, too much options. I have to make it more clean

Heheeh I could not find this expression there.

How about creating a section with customizable expressions? Would be nice!

Thanks for the effort!!

**Comment by jhbcosta** [comment]
Thanks guys!! Excellent job!! It is working fine in Brazilian Portuguese now! Cheers.

**Comment by tenkaibr** [comment]
Could you tell which expression to change the text "No events in the next days"? How can i find these expressions? Ty!

**Comment by atomic7777** [comment]
In new version, put it in your config:
noEventsForNextDaysText: 'your text'
Settings for translations are now [https://github.com/atomic7777/atomic_calendar/blob/master/README.md#translations-and-language-related-settings](here)

**Comment by tenkaibr** [comment]
Thank you my friend! You are amazing!
