### ISSUE TITLE
Dark Themes

### ISSUE THREAD

**Issue by Bluhme1** [atomic7777/atomic_calendar#23]
When I use dark themes after sunset the text becomes hard to read because it is still in black. It goes for the dates in month view and for the event-text in event view

<img width="420" alt="Skærmbillede 2019-07-09 kl  22 49 14" src="https://user-images.githubusercontent.com/50340474/60921933-ed841e00-a29b-11e9-987a-4721d1c77f5a.png">
<img width="414" alt="Skærmbillede 2019-07-09 kl  22 50 55" src="https://user-images.githubusercontent.com/50340474/60921987-0d1b4680-a29c-11e9-95a5-ad262a98ed49.png">

**Comment by atomic7777** [comment]
Do you mean you have something like automatic change of colors, day/night mode?
Do you have any of these options set: titleColor, timeColor?
If no, it should take default theme colors (night or day). If you set them manually it cant (there is only one version).
I will think about how to make it more universal, so please let me know about your settings
![col2](https://user-images.githubusercontent.com/11677097/60947039-f0106300-a2ef-11e9-941c-a96220f84408.png)
![col](https://user-images.githubusercontent.com/11677097/60947040-f0106300-a2ef-11e9-9998-373ee4376b7b.png)

**Comment by Bluhme1** [comment]
Dear Wojciech

That solved it. I had colours set for title, date and location and obviously it destroyed the possibility of automatic changing theme. (I change to DarkTheme after sunset.)

I will immediately mark the issue as solved. Perhaps it would be a good idea to mention in the documentation that you destroy the automatic changing possibility when y set the colours manually

Thanks for your help

Yours
Lars (Denmark)

**Comment by atomic7777** [comment]
Great! I just added a warning in readme. If you have any other color issues let me know.
