### ISSUE TITLE
24 h format on times missing?

### ISSUE THREAD

**Issue by isabellaalstrom** [atomic7777/atomic_calendar#3]
I can't find anything in the readme about getting 24h format on the times, is it possible? Otherwise this is an feature request :)

**Comment by atomic7777** [comment]
Thanks for feedback. I was sure 24h/12h format is changed by setting locale, that's why I didn't add any option in config. It's working in my case at least - I have 'Poland' in HA and I have 24h format by default. But I will check it and add this feature:)

**Comment by isabellaalstrom** [comment]
Where do you have locale set? Maybe I've missed something

**Comment by atomic7777** [comment]
I take language from HA and moment.js should take care of correct time format that is used in HA language/location: 
moment.locale(this.hass.language);
But I should add this option and will do it in next version.

**Comment by isabellaalstrom** [comment]
Ah okey, I use English even though  I am in Sweden

**Comment by atomic7777** [comment]
Better later than never, just added custom time format that will override the default one.
`hoursFormat` can be set to `default` `12h` `24h` or a custom one like `hh:mm a` `H:mm` etc
same like `dateFormat`

**Comment by isabellaalstrom** [comment]
Thanks! I will try soon
