### ISSUE TITLE
feature request: event whitelist

### ISSUE THREAD

**Issue by aaamoeder** [atomic7777/atomic_calendar#38]
Im aware of the blacklist function, but I have quite a few calendars where I only want to show if there is a certain word in the name of the event.. so kind of the opposite.. requiring a whitelist function

e.g. I have a google calendar from the school where my children go, they post all events containing the class 'name', so I'd only want to show events containing "6B" for my eldest..

Hopefully you find the time :)

Thanks in advance for your hard and incredibly helpful work !

**Comment by marksie1988** [comment]
Hey, I have now added whitelists to the new version of the card here: 

https://github.com/marksie1988/atomic_calendar_revive

**Comment by aaamoeder** [comment]
thank you soo much !!! people like you make HA magical !! thanks !!
