### ISSUE TITLE
Timezone when retrieving events

### ISSUE THREAD

**Issue by ozrex75** [atomic7777/atomic_calendar#5]
I live in timezone GMT+10.  I noticed that events from earlier today dropped off the calendar for today.

I found that the query to retrieve calendar events used the following querystring param: start: 2019-03-11T00:00:00Z 

This is querying with a start time of GMT 00:00:00 but it should be querying local time 00:00:00.  I added a little hack for myself changing:

let d = Z().startOf("day").format("YYYY-MM-DDTHH:mm:ss")

to

let d = Z().startOf("day").add(-10, 'hours').format("YYYY-MM-DDTHH:mm:ss")

Not sure of the correct fix to make it timezone friendly sorry.

**Comment by atomic7777** [comment]
Thank you!  I will work on this now. I was sure it's taking the correct time. I'm in GMT+1 so I haven't noticed it). I thought Google Calendar 
there were also other problems with time, for example an all-day event ends at 00:00 the following day and not at 23.59, but I have not noticed this problem.

**Comment by atomic7777** [comment]
I think it should work now in 0.7.3, that's true the component was requesting UTC time, I just added time shift based on the local time. If you can check this please let me know.
