### ISSUE TITLE
Feature Request: Hide Header

### ISSUE THREAD

**Issue by migo-dev** [atomic7777/atomic_calendar#56]
Hey, I really love the card!
It would be cool to have an option to hide the header. When putting null as title, the padding is pretty off.
Thanks for considering!

**Comment by marksie1988** [comment]
Hi @migo-dev, 

I have added this feature: https://github.com/marksie1988/atomic_calendar_revive

**Comment by m1ke-hub** [comment]
Hey @marksie1988,
Thanks for your feedback and for continuing this card! I switched to your version and tried the following options:

- name:
- name: null
- _removed "name:" completely_

But my card still looks like this:

![Bildschirmfoto 2020-05-11 um 16 12 13](https://user-images.githubusercontent.com/57773976/81571532-5cda0b00-93a2-11ea-9bb3-fa5684485519.png)

What am I missing? Could you please point me in the right direction?

Thank you very much!

PS: Let me know if I should close this and open another issue in the new repo.

**Comment by marksie1988** [comment]
Is it the card title you are trying to remove or the title for the individual event?

**Comment by m1ke-hub** [comment]
The card title. Well, I can remove it - but the top-padding is bigger than the bottom-padding.

**Comment by marksie1988** [comment]
I have raised this under https://github.com/marksie1988/atomic-calendar-revive/issues/101

**Comment by m1ke-hub** [comment]
Wow, really cool updates man - works perfect! Thank you very much for your effort 💯
