### ISSUE TITLE
Feature: Possibility to filter events

### ISSUE THREAD

**Issue by leloberg** [atomic7777/atomic_calendar#6]
I'm connected to a calendar that I don't manage, and it contains a lot of recurring events that I don't want to see. I haven't found a way to filter this within the calendar functionality in HA. I can see that you have this possibility in calendar mode in your solution, but would it be possible to do some more filtering on normal event view too?

something similar to:
filter: {not ("Breakfast")}
would hide all events named "Breakfast".

**Comment by leloberg** [comment]
I know this is maybe someway possible to achieve in the calendar mode, but I'm interested in this in event mode too :)

**Comment by atomic7777** [comment]
It was also a planned feature, when I was working on the calendar mode I thought I'l do it in event mode too. I have some fixes to do now, but I definitely will make it next versions (I have also events that I don't want to show)

**Comment by leloberg** [comment]
Perfect! If possible, I'd propose that it uses somewhat advanced filtering allowing for logical operators.

**Comment by atomic7777** [comment]
Great idea, I will first make some fixes and next I'll add filtering, probably next week (I haven't had enough time recently)

**Comment by leloberg** [comment]
Any updates on this? :) This is maybe a difficult thing to solve for all I know.

**Comment by ahd71** [comment]
Even a simple "blacklist" (to complement the current "whitelist" filter) would be very useful. Apart from that I'm really satisfied with this plugin!

**Comment by atomic7777** [comment]
Just added a "blacklist" setting - you have to make a list of comma separated words/sentences for each calendar:
```
            entities:
            - entity: calendar.kalendarz_test
              blacklist: 'something'
```
I can't work on advanced filtering because I don't have time last months so I can only try to find some time for small changes and fixes.

**Comment by ahd71** [comment]
Great! Thank you for the black list option, just what I wanted!

**Comment by ahd71** [comment]
I can confirm that the black list works as intended. 

(but the latest tracker.json still points on 0.7.5 so I had to update manually. I also get somewhat confused about the namings where comment says file is renamed to underscore but there is still a "minus" in the filename. Perhaps change "in progress"?)

**Comment by leloberg** [comment]
Blacklist now works, and I don't have the duplicate events issue anymore. That's great!
