### ISSUE TITLE
Breaks on 0.106...

### ISSUE THREAD

**Issue by cerebrate** [atomic7777/atomic_calendar#64]
...for the reason given in #63; displaying only a red error card. It looks like the existing copy in setConfig() is a shallow copy, so it fails when trying to set the subobjects.

To confirm, adding

```
 config = JSON.parse(JSON.stringify(config));
```

as the first line in setConfig() does resolve this. Doing so in app.js and re-running rollup to produce a replacement atomic_calendar.js serves as a workaround for now.

**Comment by marksie1988** [comment]
Hey @cerebrate I tried this however still have issues logged under #66 is this the same error this fix is supposed to resolve?

**Comment by marksie1988** [comment]
Hi @cerebrate, 

This has now been merged along with other features added over here:

https://github.com/marksie1988/atomic_calendar_revive
