### ISSUE TITLE
Cannot assign to read only property '0' of object '[object Array]'

### ISSUE THREAD

**Issue by marksie1988** [atomic7777/atomic_calendar#66]
I have recently started getting this error:

`Cannot assign to read only property '0' of object '[object Array]'`

After checking my calender wasnt populating, i have now fixed that and can see my entries under the states but atomiccalendar still shows this error and im not sure what is causing it.

**Comment by kalramanoj2002** [comment]
I am getting the same issue. Can someone help?

**Comment by marksie1988** [comment]
I have resolved this issue here: 
   https://github.com/marksie1988/atomic_calendar
