### ISSUE TITLE
Are you still actively maintaining this component for HA ?

### ISSUE THREAD

**Issue by UbhiTS** [atomic7777/atomic_calendar#73]
Hi, just wanted to know if you are still maintaining this library as there is a request in HACS to blacklist this repo and add a new one https://github.com/marksie1988/atomic_calendar_revive

Can you please let me know.

**Comment by atomic7777** [comment]
Unfortunately I can't maintain it anymore for personal reasons, So if you
want please add the new supported version. I'm glad to see there is
an actively developed version.
Anyway, my version still works for me the way I wanted.

czw., 30 kwi 2020 o 17:31 Tarunpreet Ubhi <notifications@github.com>
napisał(a):
