### ISSUE TITLE
Card Error

### ISSUE THREAD

**Issue by Walkingking** [atomic7777/atomic_calendar#75]
The calendar can't be loaded from Home Assistant component i am running 1.9

**Comment by Walkingking** [comment]
![chrome_xuZyShNWQQ](https://user-images.githubusercontent.com/67251572/85319818-bf392780-b487-11ea-9bc9-6c5de4c1583a.png)

This is what appears on the UI when i add it

**Comment by marksie1988** [comment]
Please fill out the issue template.

**Comment by Walkingking** [comment]
Closing. Wrong repository was opened.
