### ISSUE TITLE
Calendar mode does not always show the beginning of the month if firstDayOfWeek > 0

### ISSUE THREAD

**Issue by Shadowpheonix** [atomic7777/atomic_calendar#9]
The Calendar mode does not always show the beginning of the month.  This is more obvious if the firstDayOfWeek setting is changed away from the default, although the issue occurs either way.

When looking strictly at months in 2019...

With firstDayOfWeek set to 1 (the default), Calendar Mode shows correctly for January through August - however, when viewing September, the 1st is not displayed.

With firstDayOfWeek set to 2, the 1st is not display for April 2019.

With firstDayOfWeek set to 3, the 1st is missing from January.

With firstDayOfWeek set to 4, the 1st & 2nd are missing from January.

With firstDayOfWeek set to 5, the 1st, 2nd, and 3rd are missing from January.

With firstDayOfWeek set to 6, the 1st through 4th are missing from January.

With firstDayOfWeek set to 7, the 1st through 5th are missing from January.

With firstDayOfWeek  set to 0, the entire year displays correctly.  I did not check other years.

 (I wasn't sure if you used 1-7 or 0-6 for your scale, so I tried both)

**Comment by atomic7777** [comment]
Thanks. I will check it. I just corrected one error (the component was requesting events in UTC time instead of local time). I have never checked the firstDayOfWeek function (just added it I thought it would be good), so I will check the problem.

**Comment by atomic7777** [comment]
It should be fixed now, could you check it out?
It should should now correctly calculate the first row of the table or move it to the second one

**Comment by Shadowpheonix** [comment]
The new version seems to be working much better.  Thank you.  :)
